vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media_object:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    exercises:
    #        uri_prefix: /images/exercises
    #        upload_destination: '%kernel.project_dir%/public/images/exercises'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
